config/routes.rb
Rails.application.routes.draw do
  root 'markers#index'
  post 'markers/create', to: 'markers#create', as: 'm_c'
  get 'markers/show/:id', to: 'markers#show', as: 'm_s'
  patch 'markers/update/:id', to: 'markers#update', as: 'm_u'

  get 'categories', to: 'markers#categories_endpoint', as: 'm_c_e'

  delete 'markers/delete/:id', to: 'markers#destroy', as: 'm_d'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :markers, through: :marker_categories
    has_many :marker_categories
end

app/models/marker.rb
class Marker < ApplicationRecord
    has_many :categories, through: :marker_categories
    has_many :marker_categories
end

app/models/marker_category.rb
class MarkerCategory < ApplicationRecord
  belongs_to :marker
  belongs_to :category
end

app/models/type.rb
class Type < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  def index
    @marker_category = MarkerCategory.new
    @category = Category.new
    @marker = Marker.new
    @markers = Marker.all
    @categories = Category.all
    @marker_categories = MarkerCategory.all

  end

  def show
    @marker_categories = MarkerCategory.find(params[:id])
    @marker = Marker.new
    @category = Category.new
    @marker_category = MarkerCategory.new
  end

  def create
    if params[:marker]
      @marker = Marker.new(marker_params)
      @marker.save
      respond_to do |format|
        format.js {  }
      end
    elsif params[:category]
      @category = Category.new(category_params)
      @category.save
      respond_to do |format|
        format.js {  }
      end
    elsif params[:marker_category]
      @marker_category = MarkerCategory.new(marker_category_params)
      @marker_category.save
      respond_to do |format|
        format.js {  }
      end
    end
  end


  def update
    if params[:marker]
      @marker = Marker.find(params[:id])
      @marker.update(marker_params_edit)
      redirect_to root_path
    elsif params[:category]
      @category = Category.find(params[:id])
      @category.update(category_params)
      redirect_to root_path
    elsif params[:marker_category]
      @marker_category = MarkerCategory.find(params[:id])
      @marker_category.update(marker_category_params)
      redirect_to root_path
    end
  end



  def categories_endpoint
    @categories = Category.all
    render json: @categories.to_json
  end

  def destroy
    @marker = MarkerCategory.find(params[:id])
    @marker.destroy
    redirect_to root_path
  end

  private

  def marker_params
    params.require(:marker).permit(:url)
  end
  def marker_params_edit
    params.require(:marker).permit(:url, :id)
  end


  
  def category_params
    params.require(:category).permit(:name, :id)
  end

  def marker_category_params
    params.require(:marker_category).permit(:marker_id, :category_id, :type_relation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marcador</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markers/create.js.erb
<% if @marker %>
    var div_markers = document.getElementById("marker");
    div_markers.innerHTML += `
        <div>
            <%= @marker.url %>
        </div>
    `;
<% elsif @category %>
    var div_categories = document.getElementById("category");
    div_categories.innerHTML += `
        <div>
            <%= @category.name %>
        </div>
    `;
<% elsif @marker_category %>
    var marker_category = document.getElementById("marker_category");
    marker_category.innerHTML += `
        <div>
            url: <%= @marker_category.marker.url %>
        </div>
        <div>
            categoria: <%= @marker_category.category.name %>
        </div>
        <div>
            tipo: <%= @marker_category.type_relation %>
        </div>
        <div>
            <%= link_to 'borrar', m_d_path(@marker_category.id), method: :delete, data: {confirm: 'seguro que lo quieres borrar?'} %>
            <%= link_to 'editar', m_s_path(@marker_category.id)%>
        </div>
        <br>
        <br>
    `

<% end %>

app/views/markers/index.html.erb
<div style="display:flex; justify-content: space-around">
    <div>
        <%= form_with(url: m_c_path, model: @marker, remote: true, data: {confirm: 'seguro que esta bien escito?'}) do |m| %>
            <%= m.text_field :url, placeholder: 'ingrese la url' %>
            <%= m.submit 'guardar pagina' %>
        <% end %>
    </div>
    <div>
        <%= form_with(url: m_c_path, model: @category, remote:true) do |c| %>
            <%= c.text_field :name, placeholder: 'nombre de la categoria' %>
            <%= c.submit 'crear categoria' %>
        <% end %>
    </div>
</div>

<div style="display:flex; justify-content: space-around">
    <div id="marker">
        <% @markers.each do |marker| %>
            <div>
                <%= marker.url %>
            </div>
        <% end %>
    </div>
    <div id="category">
        <% @categories.each do |category| %>
            <div>
                <%= category.name%>
            </div>
        <% end %>
    </div>
</div>

<div>
    <h2> Asigna una categoria y un tipo a una url </h2>
    <%= form_with(url: m_c_path, model:@marker_category, remote: true) do |mc| %>
        <%= mc.select :marker_id, options_from_collection_for_select(@markers, :id, :url)%>
        <%= mc.select :category_id, options_from_collection_for_select(@categories, :id, :name)%>
        <%= mc.text_field :type_relation, placeholder: 'tipo de la pagina' %>
        <%= mc.submit 'relacionar' %>
    <% end %>
</div>

<div id="marker_category">
    <% @marker_categories.each do |markcategory| %>
        <div>
            url: <%= markcategory.marker.url %>
        </div>
        <div>
            categoria: <%= markcategory.category.name %>
        </div>
        <div>
            tipo: <%= markcategory.type_relation %>
        </div>
        <div>
            <%= link_to 'borrar', m_d_path(markcategory.id), method: :delete, data: {confirm: 'seguro que lo quieres borrar?'} %>
            <%= link_to 'editar', m_s_path(markcategory.id)%>
        </div>
        <br>
        <br>
    <% end %>
</div>

app/views/markers/show.html.erb
<%= form_with(url: m_u_path(@marker_categories.marker.id),model: @marker, local:true, method: :patch) do |f| %>
    <%= f.text_field :url, value: @marker_categories.marker.url%>
    <%= f.submit 'editar' %>
<% end %>

<br>

<%= form_with(url: m_u_path(@marker_categories.category.id),model: @category, local:true, method: :patch) do |f| %>
    <%= f.text_field :name, value: @marker_categories.category.name %>
    <%= f.submit 'editar' %>
<% end %>
<br>
<%= form_with(url: m_u_path(@marker_categories.id),model: @marker_category, local:true, method: :patch) do |f| %>
    <%= f.text_field :type_relation, value: @marker_categories.type_relation %>
    <%= f.submit 'editar' %>
<% end %>
<%= link_to 'volver al index', root_path %>